# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  


production:
  # <<: *default
  # database: db/production.sqlite3
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
